# Generated by Django 6.0.5 on 2026-05-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packagefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
